[server]
    port = "8000"
    imagePath = "./images"
    host = "http://localhost:8000"

[postgres]
    user = "postgres"
    password = "example"
    host = "localhost"
    port = "5432"
    dbname = "kanbanboard"
